version: 2.1
# orbs:
#   # use Cypress orb from CircleCI registry
#   cypress: cypress-io/cypress@1.5.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start Build"
      - restore_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npx ng build --aot --no-progress
  lint:
    docker:
      - image: circleci/node:10.15.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start Lint"
      - restore_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npx ng lint --exclude 'node_modules/**'
  prettier:
    docker:
      - image: circleci/node:10.15.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start Prettier Check"
      - restore_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm install
      - save_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run prettier
      - run: test "0" = $(git status -s -- . ":(exclude)package-lock.json" | wc -l)
  test:
    docker:
      - image: circleci/node:10.15.3-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npx ng test
      # - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  e2e-feature:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - restore_cache:
          key: nxg-sample-master
      - run:
          name: 'server start'
          command: 'npm run ci:e2e:server'
          background: true
      - run:
          name: 'cypress'
          command: 'npm run ci:e2e:run:actual'
  e2e-master:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: 'server start'
          command: 'npm run ci:e2e:server'
          background: true
      - run:
          name: 'cypress'
          command: 'npm run ci:e2e:run:base'
      - save_cache:
          key: ngx-sample-master
          paths:
            - "cypress/snapshots"
  deploy:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: echo "Deploy to GitHub Pages"
      # - restore_cache:
      #     key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}
      # - run: npm install
      # - save_cache:
      #     key: ngx-sample-{{ .Branch }}-{{ checksum "package-lock.json" }}
      #     paths:
      #       - "node_modules"
      - run: echo 'pending....'

workflows:
  version: 2.1
  workflow:
    jobs:
      - e2e-feature:
        branches:
          ignore:
            - master
      - e2e-master:
        branches:
          only:
            - master
      - test
      - lint
      - prettier
      - build:
          requires:
           - test
           - lint
           - prettier
      - deploy:
          requires:
            - build
