version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start Build"
      - run: npm install
      - run: npx ng build --aot --no-progress
  lint:
    docker:
      - image: circleci/node:10.15.3-stretch-browsers
    steps:
      - checkout
      - run: npx ng lint

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - lint:
          requires:
           - build
