version: 2.1
# orbs:
#   # use Cypress orb from CircleCI registry
#   cypress: cypress-io/cypress@1.5.1
commands:
  restore_npm:
    steps:
      - restore_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package.json" }}

  save_npm:
    steps:
      - save_cache:
          key: ngx-sample-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
  install_notofont:
    steps:
      - run: apt-get install -y fonts-noto-cjk

executors:
  node:
    docker:
      - image: circleci/node:10.15.3-stretch-browsers
  cypress-cjk:
    docker:
      - image: cypress/base:10
    # environment:
    #   - LANG: ja_JP.UTF-8
    #   - LC_CTYPE: ja_JP.UTF-8

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: echo "Start Build"
      - restore_npm
      - run: npm install
      - save_npm
      - run: npx ng build --aot --no-progress
  lint:
    executor: node
    steps:
      - checkout
      - run: echo "Start Lint"
      - restore_npm
      - run: npm install
      - save_npm
      - run: npx ng lint --exclude 'node_modules/**'
  prettier:
    executor: node
    steps:
      - checkout
      - run: echo "Start Prettier Check"
      - restore_npm
      - run: npm install
      - save_npm
      - run: npm run prettier
      - run: git status
      - run: test "0" = $(git status -s -- . ":(exclude)package-lock.json" | wc -l)
  test:
    executor: node
    steps:
      - checkout
      - restore_npm
      - run: npm install
      - save_npm
      - run: npx ng test
  e2e-feature:
    executor: cypress-cjk
    steps:
      - install_notofont
      - checkout
      - restore_npm
      - run: npm install
      - save_npm
      - restore_cache:
          key: ngx-sample-base-snapshot-{{ .Revision }}
      - run:
          name: 'server start'
          command: 'npm run ci:e2e:server'
          background: true
      - run:
          name: 'cypress'
          command: 'npm run ci:e2e:run:actual'
      - store_test_results:
          path: "e2e-results"
          when: always
      - store_artifacts:
          path: "e2e-results"
          destination: cypress-report
          when: always
      - store_artifacts:
          path: "cypress/snapshots"
          destination: cypress-snapshots
          when: always
  e2e-master:
    executor: cypress-cjk
    steps:
      - install_notofont
      - checkout
      - run:
          name: 'masterとの比較用checkout'
          command: |
            git checkout master
            git reset --hard origin/master
      - restore_npm
      - run: npm install
      - run:
          name: 'server start'
          command: 'npm run ci:e2e:server'
          background: true
      - run:
          name: 'cypress'
          command: 'npm run ci:e2e:run:base'
      - save_cache:
          key: ngx-sample-base-snapshot-{{ .Revision }}
          paths:
            - "cypress/snapshots"
      - store_test_results:
          path: "e2e-results"
          when: always
      - store_artifacts:
          path: "e2e-results"
          destination: cypress-report
          when: always
      - store_artifacts:
          path: "cypress/snapshots"
          destination: cypress-snapshots
          when: always
  deploy:
    executor: node
    steps:
      - run: echo "Deploy to GitHub Pages"
      # - checkout
      # - restore_npm
      # - run: npm install
      # - save_npm
      # - run:
      #     name: 'git config'
      #     command: |
      #       git config user.email "swfz+circleci@users.noreply.github.com"
      #       git config user.name "swfz+circleci"
      # - run: npm run ghpages

workflows:
  version: 2.1
  workflow:
    jobs:
      - e2e-feature:
          requires:
            - e2e-master
          filters:
            branches:
              ignore:
                - master
      - e2e-master
      - test
      - lint
      - prettier
      - build:
          requires:
           - test
           - lint
           - prettier
      - deploy:
          requires:
            - build
            - e2e-master
          filters:
            branches:
              only:
                - master
