name: ci
on: [push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles(format('{0}{1}', github.workspace, '/package.json')) }}

      - name: npm install, prettier
        run: |
          npm install
          npm run prettier:check
        env:
          CI: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles(format('{0}{1}', github.workspace, '/package.json')) }}

      - name: npm install, lint
        run: |
          npm install
          npx ng lint --exclude 'node_modules/**'
        env:
          CI: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles(format('{0}{1}', github.workspace, '/package.json')) }}

      - name: npm install, test
        run: |
          npm install
          npm run test
        env:
          CI: true

